services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: quickpoll
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Expose to host so frontend can reach it
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/quickpoll
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
